
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLySanBongMini.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DatSan
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DatSan()
    {

        this.HoaDons = new HashSet<HoaDon>();

    }


    public int MaDatSan { get; set; }

    public int MaKH { get; set; }

    public int MaSan { get; set; }

    public System.DateTime TGBatDau { get; set; }

    public System.DateTime TGKetThuc { get; set; }

    public Nullable<decimal> TongTien { get; set; }

    public string TrangThai { get; set; }



    public virtual KhachHang KhachHang { get; set; }

    public virtual SanBong SanBong { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HoaDon> HoaDons { get; set; }

}

}
