
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLySanBongMini.Models
{

using System;
    using System.Collections.Generic;
    
public partial class HoaDon
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public HoaDon()
    {

        this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();

    }


    public int MaHD { get; set; }

    public Nullable<int> MaDatSan { get; set; }

    public int MaNV { get; set; }

    public Nullable<System.DateTime> NgayLap { get; set; }

    public Nullable<decimal> TongTien { get; set; }

    public string LoaiHD { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }

    public virtual DatSan DatSan { get; set; }

    public virtual NhanVien NhanVien { get; set; }

}

}
