

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLySanBongMini.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class QLYSANBONGMINIEntities : DbContext
{
    public QLYSANBONGMINIEntities()
        : base("name=QLYSANBONGMINIEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<ChiTietHoaDon> ChiTietHoaDons { get; set; }

    public virtual DbSet<DatSan> DatSans { get; set; }

    public virtual DbSet<HoaDon> HoaDons { get; set; }

    public virtual DbSet<KhachHang> KhachHangs { get; set; }

    public virtual DbSet<NhanVien> NhanViens { get; set; }

    public virtual DbSet<SanBong> SanBongs { get; set; }

    public virtual DbSet<MonAn> MonAns { get; set; }

}

}

