
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLySanBongMini.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MonAn
{

    public int MaMon { get; set; }

    public string TenMon { get; set; }

    public string LoaiMon { get; set; }

    public decimal DonGia { get; set; }

    public string MoTa { get; set; }

    public bool ConHang { get; set; }

}

}
