
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLySanBongMini.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SanBong
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SanBong()
    {

        this.DatSans = new HashSet<DatSan>();

    }


    public int MaSan { get; set; }

    public string TenSan { get; set; }

    public string LoaiSan { get; set; }

    public decimal GiaThueGio { get; set; }

    public string TrangThai { get; set; }

    public string HinhAnh { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DatSan> DatSans { get; set; }

}

}
